config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'restaurants#index'
  resources :restaurants, only: %i[new create show index] do
    collection do
      get :search, as: :search
    end
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  CATEGORIES = %w[chinese italian japanese french belgian american english].sort.freeze
  has_many :reviews, dependent: :destroy
  validates_associated :reviews
  validates_presence_of :name, :address, :category, :phone_number
  validates_uniqueness_of :address, :phone_number

  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  RATING = (0..5).to_a

  belongs_to :restaurant
  validates_presence_of :rating, :content
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

class RestaurantsController < ApplicationController
  before_action :set_restaurants, only: %i[show update destroy]
  def index
    @restaurants = Restaurant.all
    @rating = '<i class="far fa-star"></i>'
  end

  def show
    @rating = '<i class="far fa-star"></i>'
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def search
    @results = Restaurant.where('name LIKE ?', "%#{params[:name]}%")
    @results = if params[:name].empty?
                 @message = "You didn't enter anything!"
                 zero_results
               elsif @results.count.zero?
                 @message = "No results for #{params[:name]}."
                 @count = 0
                 zero_results
               else
                 @count = @results.count
                 @message = "Here are all the results for #{params[:name]}:"
                 Restaurant.where('name LIKE ?', "%#{params[:name]}%")
               end
  end


  private

  def zero_results
    @count = 0
    []
  end

  def set_restaurants
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/layouts/_search_form.html.erb
<%= form_with url: restaurants_search_path, html: {class: "form-inline"}, method: :get do |f| %>
 <div class="row">
    <div class="col">
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="col">
  <%= f.submit "Search", class: 'btn btn-outline-success my-2 my-sm-0' %>
  </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-light bg-light">
  <div class="container">
  <%= link_to "Home", restaurants_path, class: 'navbar-brand' %>
  <%= link_to "Add a restaurant", new_restaurant_path %>
  <%= render "search_form" %>
  </div>
</nav>
    <%= yield %>


  </body>

</html>

app/views/restaurants/_form.html.erb
<div class="col-4">
<%= simple_form_for(restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.select :category, category: Restaurant::CATEGORIES %>
<%= f.submit "Add Restaurant", class: 'btn btn-primary align-items-center'%>
<% end %>
</div>

app/views/restaurants/_search_form.html.erb
<%= form_with url: search_restaurants_path, html: {class: "form-inline"}, method: :get do |f| %>
 <div class="row">
  <div class="col-6">
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="col">
  <%= f.submit "Search", class: 'btn btn-outline-success my-2 my-sm-0' %>
  </div>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit article</h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class="container mt-3 mb-3">

<h1 class=" mb-3 headings-sans-serif">Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
      | <%= restaurant.address %> | <%= restaurant.category.capitalize %> | Average rating: <%sum = restaurant.reviews.map { |review|  review.rating.to_f } %>
      <% if sum == [] %>
       <small> (No reviews. <%= avg = link_to "Add a review", new_restaurant_review_path(restaurant) %> )</small>
      <% else %>
        <% avg = sum.sum / sum.length %>
        <% avg.round.times do %>
          <i class="far fa-star"></i>
        <% end %>
      <% end %>

    </li>
    <br>
  <% end %>
</ul>
<hr>
</div>

app/views/restaurants/new.html.erb
<div class="container justify-content-center">
<div class="row justify-content-md-center">
  <div class="col-12">
  <h1>Add a new restaurant</h1>
  </div>
</div>
  <div class="row justify-content-md-center">
<%= render "form", restaurant: @restaurant %>
</div>

</div>

app/views/restaurants/search.html.erb
<div class="container">
  <h1 class="headings-sans-serif">Search results (<%= @count %>) </h1>

  <h2> <%= @message %> </h2>
  <ul>
    <% @results.each do |restaurant| %>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
    <% end %>
  </ul>
</div>

app/views/restaurants/show.html.erb
<div class="container">

<div class="info">
<h1> <%= @restaurant.name %></h1>
<p> <%= @restaurant.address %> </p>
<p> <%= @restaurant.phone_number %> </p>
</div>
<ul>
<% @restaurant.reviews.each do |review| %>
  <li class="review "><%= review.content %> |
   <% review.rating.times do %>
    <small><%= sanitize '<i class="far fa-star"></i>' %></small>
    <% end %>
  </li>
  <br>
<% end %>
</ul>

<hr>
<%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>




</div>

app/views/reviews/_search_form.html.erb
<%= form_with url: search_restaurants_path, html: {class: "form-inline"}, method: :get do |f| %>
 <div class="row">
    <div class="col">
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="col">
  <%= f.submit "Search", class: 'btn btn-outline-success my-2 my-sm-0' %>
  </div>
  </div>
<% end %>

app/views/reviews/new.html.erb
<div class="container justify-content">
<h1>Add a review for  <%= @restaurant.name %></h1>

<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <div class="form-group col-md-6">
  <%= f.input :content, class: "form-control"%>
</div>
  <div class="form-group">
    <div class="btn-group-vertical">
      <%= f.select :rating, "Choose a rating from 0-5": Review::RATING  %>
    </div>
  </div>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
</div>